---
AWSTemplateFormatVersion: '2010-09-09'
Description: US-EAST-1 ONLY! Generate Route53 health checks.
Parameters:
  Email:
    Type: String
    Description: Email address to notify when an alarm is triggered
Resources:
  NotifyMe:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Ref: Email
        Protocol: email

  awsCraigHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Port: '80'
        Type: HTTP
        ResourcePath: "/"
        FullyQualifiedDomainName: craig.mayhew.io
        RequestInterval: '30'
        FailureThreshold: '3'
      HealthCheckTags:
      - Key: Application
        Value:
          Ref: AWS::StackName

  awsCraigAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Ref: NotifyMe
      AlarmDescription: Alert when craig's website is down
      ComparisonOperator: LessThanThreshold
      Dimensions:
      - Name: HealthCheckId
        Value:
          Ref: awsCraigHealthCheck
      EvaluationPeriods: '3'
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Period: '60'
      Statistic: Minimum
      Threshold: '1'
  
